package view;

import dao.DaoTask;
import dao.DaoUser;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.ModelTask;
import model.ModelUser;

/**
 *
 * @author rodri
 */
public class CreateTaskView extends javax.swing.JFrame {

    ModelTask modelTask = new ModelTask();
    DaoTask daoTask = new DaoTask();
    DaoUser daoUser = new DaoUser();
    ModelUser modelUser = new ModelUser();

    /**
     * Creates new form CreateTaskView
     */
    public CreateTaskView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createTaskTxt = new javax.swing.JLabel();
        nameTaskTxt = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        designNameTask = new javax.swing.JLabel();
        createdDate = new javax.swing.JLabel();
        txtCreatedDate = new javax.swing.JFormattedTextField();
        designCreatedDate = new javax.swing.JLabel();
        designEndDate = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JFormattedTextField();
        txtTags = new javax.swing.JLabel();
        designEndDateBacc = new javax.swing.JLabel();
        jComboBoxTags = new javax.swing.JComboBox<>();
        txtCreate = new javax.swing.JLabel();
        btnCreate = new javax.swing.JLabel();
        calendarIcon = new javax.swing.JLabel();
        frameBlue = new javax.swing.JLabel();
        backgroundWhite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(829, 449));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createTaskTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Create Task.png"))); // NOI18N
        createTaskTxt.setMaximumSize(new java.awt.Dimension(164, 40));
        createTaskTxt.setMinimumSize(new java.awt.Dimension(164, 40));
        createTaskTxt.setPreferredSize(new java.awt.Dimension(164, 40));
        getContentPane().add(createTaskTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 13, 212, 40));

        nameTaskTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Name Task.png"))); // NOI18N
        nameTaskTxt.setMaximumSize(new java.awt.Dimension(89, 15));
        nameTaskTxt.setMinimumSize(new java.awt.Dimension(89, 15));
        nameTaskTxt.setPreferredSize(new java.awt.Dimension(89, 15));
        getContentPane().add(nameTaskTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 87, 89, 15));

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.setBorder(null);
        txtName.setMaximumSize(new java.awt.Dimension(240, 17));
        txtName.setMinimumSize(new java.awt.Dimension(240, 17));
        txtName.setPreferredSize(new java.awt.Dimension(240, 17));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 250, 20));

        designNameTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        designNameTask.setMaximumSize(new java.awt.Dimension(265, 37));
        designNameTask.setMinimumSize(new java.awt.Dimension(265, 37));
        designNameTask.setPreferredSize(new java.awt.Dimension(265, 37));
        getContentPane().add(designNameTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 111, 280, 37));

        createdDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Created Date.png"))); // NOI18N
        createdDate.setMaximumSize(new java.awt.Dimension(89, 15));
        createdDate.setMinimumSize(new java.awt.Dimension(89, 15));
        createdDate.setPreferredSize(new java.awt.Dimension(89, 15));
        getContentPane().add(createdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 165, 89, 20));

        txtCreatedDate.setBackground(new java.awt.Color(255, 255, 255));
        txtCreatedDate.setBorder(null);
        txtCreatedDate.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtCreatedDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCreatedDate.setMaximumSize(null);
        txtCreatedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreatedDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtCreatedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 80, 30));

        designCreatedDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DateRect.png"))); // NOI18N
        designCreatedDate.setMaximumSize(null);
        getContentPane().add(designCreatedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 187, -1, -1));

        designEndDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/End Date.png"))); // NOI18N
        designEndDate.setMaximumSize(new java.awt.Dimension(89, 15));
        designEndDate.setMinimumSize(new java.awt.Dimension(89, 15));
        designEndDate.setPreferredSize(new java.awt.Dimension(89, 15));
        getContentPane().add(designEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 165, 89, 15));

        txtEndDate.setBackground(new java.awt.Color(255, 255, 255));
        txtEndDate.setBorder(null);
        txtEndDate.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtEndDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEndDate.setMaximumSize(null);
        getContentPane().add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 80, 30));

        txtTags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tags (2).png"))); // NOI18N
        txtTags.setMaximumSize(new java.awt.Dimension(38, 15));
        txtTags.setMinimumSize(new java.awt.Dimension(38, 15));
        txtTags.setPreferredSize(new java.awt.Dimension(38, 15));
        getContentPane().add(txtTags, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 87, 38, 15));

        designEndDateBacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DateRect.png"))); // NOI18N
        getContentPane().add(designEndDateBacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 187, 135, 37));

        jComboBoxTags.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTags.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxTags.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxTags.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick an Option", "Science", "English", "Math", "History" }));
        jComboBoxTags.setBorder(null);
        jComboBoxTags.setMaximumSize(new java.awt.Dimension(163, 172));
        jComboBoxTags.setMinimumSize(new java.awt.Dimension(163, 172));
        getContentPane().add(jComboBoxTags, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 111, 163, 40));

        txtCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Create (1).png"))); // NOI18N
        txtCreate.setToolTipText("");
        txtCreate.setMaximumSize(new java.awt.Dimension(55, 15));
        txtCreate.setMinimumSize(new java.awt.Dimension(55, 15));
        txtCreate.setPreferredSize(new java.awt.Dimension(55, 15));
        txtCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCreateMouseClicked(evt);
            }
        });
        getContentPane().add(txtCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 279, 55, 20));

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLogin.png"))); // NOI18N
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 273, 151, 37));

        calendarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 14 (1).png"))); // NOI18N
        calendarIcon.setToolTipText("");
        getContentPane().add(calendarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 302, 259));

        frameBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame.png"))); // NOI18N
        getContentPane().add(frameBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backgroundWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUpScreen.png"))); // NOI18N
        getContentPane().add(backgroundWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCreatedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreatedDateActionPerformed

    }//GEN-LAST:event_txtCreatedDateActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        try {
            String nameTask = txtName.getText();
            String create = txtCreatedDate.getText();
            String end = txtEndDate.getText();

            if (nameTask.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Empty Field");
            } else {
                modelTask.setName_Task(txtName.getText());
                modelTask.setCreated_Task(txtCreatedDate.getText());
                modelTask.setEnd_Task(txtEndDate.getText());
                String nameUser = JOptionPane.showInputDialog(null, "Enter your name to continue the action");
                modelUser.setName_User(nameUser);
                int idUser = daoUser.returnIdUser(modelUser);
                if (nameUser == null) {
                    JOptionPane.showMessageDialog(null, "Cancellation done successfully, the create screen will be closed!");
                    dispose();
                } else if (nameUser.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Empty Field");
                } else if (idUser == 0) {
                    JOptionPane.showMessageDialog(null, "The user you entered does not exist");
                    dispose();
                } else {
                    modelTask.setTags_Task(jComboBoxTags.getSelectedItem().toString());
                    modelTask.setUser_tb_ID_UserFk(idUser);
                    if (daoTask.insertTask(modelTask)) {
                        JOptionPane.showMessageDialog(null, modelTask.getName_Task() + " task was successfully registered");

                    }
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCreateMouseClicked

    private void txtCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCreateMouseClicked

    }//GEN-LAST:event_txtCreateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTaskView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTaskView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTaskView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTaskView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTaskView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundWhite;
    private javax.swing.JLabel btnCreate;
    private javax.swing.JLabel calendarIcon;
    private javax.swing.JLabel createTaskTxt;
    private javax.swing.JLabel createdDate;
    private javax.swing.JLabel designCreatedDate;
    private javax.swing.JLabel designEndDate;
    private javax.swing.JLabel designEndDateBacc;
    private javax.swing.JLabel designNameTask;
    private javax.swing.JLabel frameBlue;
    private javax.swing.JComboBox<String> jComboBoxTags;
    private javax.swing.JLabel nameTaskTxt;
    private javax.swing.JLabel txtCreate;
    private javax.swing.JFormattedTextField txtCreatedDate;
    private javax.swing.JFormattedTextField txtEndDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel txtTags;
    // End of variables declaration//GEN-END:variables
}
