package view;

import dao.DaoTask;
import dao.DaoUser;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelTask;
import model.ModelUser;

/**
 *
 * @author rodri
 */
public class ListView extends javax.swing.JFrame {

    DaoTask daoTask = new DaoTask();
    ModelTask modelTask = new ModelTask();
    ModelUser modelUser = new ModelUser();
    DaoUser daoUSer = new DaoUser();

    /**
     * Creates new form ListView
     */
    private void listTask() {
        List<ModelTask> list = daoTask.listTask(modelTask);
        DefaultTableModel table = (DefaultTableModel) TaskTable.getModel();
        table.setNumRows(0);
        list.forEach((t) -> {
            table.addRow(new Object[]{
                t.getID_Task(),
                t.getName_Task(),
                t.getTags_Task(),
                t.getCreated_Task(),
                t.getEnd_Task()
            });
        });
    }

    public ListView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuvemIcon = new javax.swing.JLabel();
        taskNotesIcon = new javax.swing.JLabel();
        updateTask = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        created = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        tags = new javax.swing.JLabel();
        tableUpdate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaskTable = new javax.swing.JTable();
        frameBlue = new javax.swing.JLabel();
        backgroundWhite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(829, 449));
        setMinimumSize(new java.awt.Dimension(829, 449));
        setPreferredSize(new java.awt.Dimension(829, 449));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuvemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuvem.png"))); // NOI18N
        getContentPane().add(nuvemIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 26, 25, 16));

        taskNotesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SkyNotes.png"))); // NOI18N
        taskNotesIcon.setMaximumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setMinimumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setName(""); // NOI18N
        taskNotesIcon.setPreferredSize(new java.awt.Dimension(119, 34));
        getContentPane().add(taskNotesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 17, 119, 40));

        updateTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/To-Do List.png"))); // NOI18N
        updateTask.setMaximumSize(new java.awt.Dimension(164, 40));
        updateTask.setMinimumSize(new java.awt.Dimension(164, 40));
        updateTask.setPreferredSize(new java.awt.Dimension(164, 40));
        getContentPane().add(updateTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 164, 40));

        id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ID (1).png"))); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 60));

        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Task Name (1).png"))); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 110, 90, 40));

        created.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Created Date (1).png"))); // NOI18N
        getContentPane().add(created, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 120, 120, 20));

        end.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/End Date (1).png"))); // NOI18N
        getContentPane().add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 120, 80, 20));

        tags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tags (1).png"))); // NOI18N
        getContentPane().add(tags, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 120, 70, 20));

        tableUpdate.setBackground(new java.awt.Color(255, 255, 255));
        tableUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Col Titles BG (1).png"))); // NOI18N
        tableUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(tableUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 760, 140));

        TaskTable.setBackground(new java.awt.Color(255, 255, 255));
        TaskTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "I-", "-", "-", "-", "-"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TaskTable.setFocusable(false);
        TaskTable.setGridColor(new java.awt.Color(255, 255, 255));
        TaskTable.setMinimumSize(new java.awt.Dimension(712, 293));
        TaskTable.setPreferredSize(new java.awt.Dimension(712, 293));
        TaskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TaskTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 590, 190));

        frameBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame.png"))); // NOI18N
        getContentPane().add(frameBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 829, 449));

        backgroundWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUpScreen.png"))); // NOI18N
        getContentPane().add(backgroundWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUpdateMouseClicked

    }//GEN-LAST:event_tableUpdateMouseClicked

    private void TaskTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_TaskTableMouseClicked


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String nameUser = JOptionPane.showInputDialog(null, "Enter your name to continue the action");
        modelUser.setName_User(nameUser);
        int idUser = daoTask.returnIdUser(modelUser);
        if (nameUser == null) {
            JOptionPane.showMessageDialog(null, "Cancellation done successfully, the listed at screen will be closed!");
            dispose();
        } else if (nameUser.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Field");
            OptionsView optionsView = new OptionsView();
            optionsView.setVisible(true);
            dispose();
        } else if (idUser == 0) {
            JOptionPane.showMessageDialog(null, "The user you entered does not exist");
        } else {
            modelTask.setUser_tb_ID_UserFk(idUser);
            daoTask.listTask(modelTask);
        }


    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        listTask();


    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TaskTable;
    private javax.swing.JLabel backgroundWhite;
    private javax.swing.JLabel created;
    private javax.swing.JLabel end;
    private javax.swing.JLabel frameBlue;
    private javax.swing.JLabel id;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nuvemIcon;
    private javax.swing.JLabel tableUpdate;
    private javax.swing.JLabel tags;
    private javax.swing.JLabel taskNotesIcon;
    private javax.swing.JLabel updateTask;
    // End of variables declaration//GEN-END:variables
}
