package view;
import dao.DaoUser;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.ModelUser;

/**
 *
 * @author rodri
 */
public class LoginView extends javax.swing.JFrame {

    ModelUser modelUser = new ModelUser();
    DaoUser daoUser = new DaoUser();

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtemailAddressDesign = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        backgroundEmailAddress = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        dPassword = new javax.swing.JLabel();
        dateIcon = new javax.swing.JLabel();
        designWelcome = new javax.swing.JLabel();
        nuvemIcon = new javax.swing.JLabel();
        taskNotesIcon = new javax.swing.JLabel();
        txtSignUp = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        txtNotRegistered = new javax.swing.JLabel();
        frameBlue = new javax.swing.JLabel();
        backgroundWhite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(829, 449));
        setMinimumSize(new java.awt.Dimension(829, 449));
        setName("LoginView"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemailAddressDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoEmail (2).png"))); // NOI18N
        txtemailAddressDesign.setMaximumSize(new java.awt.Dimension(91, 29));
        txtemailAddressDesign.setMinimumSize(new java.awt.Dimension(91, 29));
        txtemailAddressDesign.setPreferredSize(new java.awt.Dimension(91, 29));
        getContentPane().add(txtemailAddressDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 105, 91, 29));

        txtEmailAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailAddress.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailAddress.setBorder(null);
        txtEmailAddress.setMaximumSize(new java.awt.Dimension(240, 17));
        txtEmailAddress.setMinimumSize(new java.awt.Dimension(240, 17));
        txtEmailAddress.setPreferredSize(new java.awt.Dimension(240, 17));
        getContentPane().add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 250, 20));

        backgroundEmailAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        getContentPane().add(backgroundEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 134, 270, 37));

        txtPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoPassword.png"))); // NOI18N
        txtPassword.setMaximumSize(new java.awt.Dimension(91, 29));
        txtPassword.setMinimumSize(new java.awt.Dimension(91, 29));
        txtPassword.setPreferredSize(new java.awt.Dimension(91, 29));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 175, 91, 29));

        txtPassword1.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword1.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword1.setBorder(null);
        txtPassword1.setMaximumSize(new java.awt.Dimension(250, 30));
        txtPassword1.setMinimumSize(new java.awt.Dimension(250, 30));
        txtPassword1.setPreferredSize(new java.awt.Dimension(230, 30));
        txtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 230, 20));

        dPassword.setForeground(new java.awt.Color(0, 0, 0));
        dPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        getContentPane().add(dPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 202, 270, 37));

        dateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DateIcon.png"))); // NOI18N
        dateIcon.setToolTipText("");
        getContentPane().add(dateIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 302, 259));

        designWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Welcome SkyNotes.png"))); // NOI18N
        designWelcome.setMaximumSize(new java.awt.Dimension(164, 40));
        designWelcome.setMinimumSize(new java.awt.Dimension(164, 40));
        designWelcome.setPreferredSize(new java.awt.Dimension(164, 40));
        getContentPane().add(designWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 26, 260, 40));

        nuvemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuvem.png"))); // NOI18N
        getContentPane().add(nuvemIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 26, 25, 16));

        taskNotesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SkyNotes.png"))); // NOI18N
        taskNotesIcon.setMaximumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setMinimumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setName(""); // NOI18N
        taskNotesIcon.setPreferredSize(new java.awt.Dimension(119, 34));
        getContentPane().add(taskNotesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 17, 119, 40));

        txtSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        txtSignUp.setToolTipText("");
        txtSignUp.setMaximumSize(new java.awt.Dimension(75, 23));
        txtSignUp.setMinimumSize(new java.awt.Dimension(75, 23));
        txtSignUp.setPreferredSize(new java.awt.Dimension(75, 23));
        txtSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSignUpMouseClicked(evt);
            }
        });
        getContentPane().add(txtSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 298, 50, 23));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLogin.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 292, 151, 37));

        txtNotRegistered.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoEmail.png"))); // NOI18N
        txtNotRegistered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNotRegisteredMouseClicked(evt);
            }
        });
        getContentPane().add(txtNotRegistered, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, 30));

        frameBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame.png"))); // NOI18N
        getContentPane().add(frameBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backgroundWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUpScreen.png"))); // NOI18N
        getContentPane().add(backgroundWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 829, 449));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed


    }//GEN-LAST:event_txtPassword1ActionPerformed
    private void clean() {
        txtEmailAddress.setText("");
        txtPassword1.setText("");
    }
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        try {
            String email = txtEmailAddress.getText();
            String password = txtPassword1.getText();
            modelUser.setEmail_User(email);
            modelUser.setPassword_User(password);
            if (!modelUser.getEmail_User().isEmpty() && !modelUser.getPassword_User().isEmpty()) {
                if (daoUser.validateLogin(modelUser)) {
                    OptionsView optionsView = new OptionsView();
                    optionsView.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect e-mail or password");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Empty Field");
            }
            clean();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void txtSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSignUpMouseClicked
        // TODO add your handling code here:
        btnLoginMouseClicked(evt);
    }//GEN-LAST:event_txtSignUpMouseClicked

    private void txtNotRegisteredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNotRegisteredMouseClicked
        // TODO add your handling code here:
        SignUpView signUpView = new SignUpView();
        signUpView.setVisible(true);
    }//GEN-LAST:event_txtNotRegisteredMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundEmailAddress;
    private javax.swing.JLabel backgroundWhite;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel dPassword;
    private javax.swing.JLabel dateIcon;
    private javax.swing.JLabel designWelcome;
    private javax.swing.JLabel frameBlue;
    private javax.swing.JLabel nuvemIcon;
    private javax.swing.JLabel taskNotesIcon;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JLabel txtNotRegistered;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JLabel txtSignUp;
    private javax.swing.JLabel txtemailAddressDesign;
    // End of variables declaration//GEN-END:variables
}
