package view;

/**
 *
 * @author rodri
 */
public class OptionsView extends javax.swing.JFrame {

    /**
     * Creates new form OptionsView
     */
    public OptionsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuvemIcon1 = new javax.swing.JLabel();
        taskNotesIcon = new javax.swing.JLabel();
        designOptionsView = new javax.swing.JLabel();
        btnCreate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnListAt = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();
        lblDelete1 = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        lblUpdate1 = new javax.swing.JLabel();
        dateIcon = new javax.swing.JLabel();
        frameBlue = new javax.swing.JLabel();
        backgroundWhite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(829, 449));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuvemIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuvem.png"))); // NOI18N
        getContentPane().add(nuvemIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 26, 25, 16));

        taskNotesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SkyNotes.png"))); // NOI18N
        taskNotesIcon.setMaximumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setMinimumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setName(""); // NOI18N
        taskNotesIcon.setPreferredSize(new java.awt.Dimension(119, 34));
        getContentPane().add(taskNotesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 17, 119, 40));

        designOptionsView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Options View.png"))); // NOI18N
        designOptionsView.setMaximumSize(new java.awt.Dimension(164, 40));
        designOptionsView.setMinimumSize(new java.awt.Dimension(164, 40));
        designOptionsView.setPreferredSize(new java.awt.Dimension(164, 40));
        getContentPane().add(designOptionsView, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 26, 190, 40));

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCreate (1).png"))); // NOI18N
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 138, 45, 45));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 12.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 138, 45, 45));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 13.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 138, 45, 45));

        btnListAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 14.png"))); // NOI18N
        btnListAt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListAtMouseClicked(evt);
            }
        });
        getContentPane().add(btnListAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 138, 45, 45));

        lblCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Create.png"))); // NOI18N
        lblCreate.setMaximumSize(new java.awt.Dimension(51, 15));
        lblCreate.setMinimumSize(new java.awt.Dimension(51, 15));
        lblCreate.setPreferredSize(new java.awt.Dimension(51, 15));
        lblCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateMouseClicked(evt);
            }
        });
        getContentPane().add(lblCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 192, 51, 15));

        lblDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        lblDelete1.setMaximumSize(new java.awt.Dimension(51, 15));
        lblDelete1.setMinimumSize(new java.awt.Dimension(51, 15));
        lblDelete1.setPreferredSize(new java.awt.Dimension(51, 15));
        lblDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDelete1MouseClicked(evt);
            }
        });
        getContentPane().add(lblDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 192, 51, 15));

        lblUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Update.png"))); // NOI18N
        lblUpdate.setToolTipText("");
        lblUpdate.setMaximumSize(new java.awt.Dimension(51, 15));
        lblUpdate.setMinimumSize(new java.awt.Dimension(51, 15));
        lblUpdate.setName(""); // NOI18N
        lblUpdate.setPreferredSize(new java.awt.Dimension(51, 15));
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdateMouseEntered(evt);
            }
        });
        getContentPane().add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 192, 51, 15));

        lblUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Listed at.png"))); // NOI18N
        lblUpdate1.setToolTipText("");
        lblUpdate1.setMaximumSize(new java.awt.Dimension(51, 15));
        lblUpdate1.setMinimumSize(new java.awt.Dimension(51, 15));
        lblUpdate1.setName(""); // NOI18N
        lblUpdate1.setPreferredSize(new java.awt.Dimension(51, 15));
        lblUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdate1MouseClicked(evt);
            }
        });
        getContentPane().add(lblUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 192, 60, 15));

        dateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/womannotes.png"))); // NOI18N
        dateIcon.setText("jLabel5");
        dateIcon.setMaximumSize(new java.awt.Dimension(251, 290));
        dateIcon.setMinimumSize(new java.awt.Dimension(251, 290));
        dateIcon.setPreferredSize(new java.awt.Dimension(251, 290));
        getContentPane().add(dateIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 63, 251, 290));

        frameBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame.png"))); // NOI18N
        getContentPane().add(frameBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 829, 449));

        backgroundWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUpScreen.png"))); // NOI18N
        getContentPane().add(backgroundWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 829, 449));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked

        CreateTaskView createTaskView = new CreateTaskView();
        createTaskView.setVisible(true);

    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

        DeleteTask deleteTask = new DeleteTask();
        deleteTask.setVisible(true);

    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked

        UpdateTask updateTask = new UpdateTask();
        updateTask.setVisible(true);


    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnListAtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListAtMouseClicked
  
        ListView listView = new ListView();
        listView.setVisible(true);


    }//GEN-LAST:event_btnListAtMouseClicked

    private void lblCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseClicked
    
        btnCreateMouseClicked(evt);
    }//GEN-LAST:event_lblCreateMouseClicked

    private void lblDelete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete1MouseClicked

        btnDeleteMouseClicked(evt);
    }//GEN-LAST:event_lblDelete1MouseClicked

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked

        btnUpdateMouseClicked(evt);
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate1MouseClicked
 
        btnListAtMouseClicked(evt);
    }//GEN-LAST:event_lblUpdate1MouseClicked

    private void lblUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseEntered
  
    }//GEN-LAST:event_lblUpdateMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OptionsView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundWhite;
    private javax.swing.JLabel btnCreate;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnListAt;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JLabel dateIcon;
    private javax.swing.JLabel designOptionsView;
    private javax.swing.JLabel frameBlue;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDelete1;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUpdate1;
    private javax.swing.JLabel nuvemIcon1;
    private javax.swing.JLabel taskNotesIcon;
    // End of variables declaration//GEN-END:variables
}
