package view;

import dao.DaoUser;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.ModelUser;

/**
 *
 * @author rodri
 */
public class SignUpView extends javax.swing.JFrame {

    ModelUser modelUser = new ModelUser();
    DaoUser daoUser = new DaoUser();

    /**
     * Creates new form SignUpView
     */
    public SignUpView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFullName = new javax.swing.JTextField();
        backgroundName = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        dEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        dPassword = new javax.swing.JLabel();
        txtFullNameDesign = new javax.swing.JLabel();
        txtEmailDesign = new javax.swing.JLabel();
        txtPasswordDesign = new javax.swing.JLabel();
        designSignUp = new javax.swing.JLabel();
        nuvemIcon = new javax.swing.JLabel();
        taskNotesIcon = new javax.swing.JLabel();
        womanSkateIcon = new javax.swing.JLabel();
        txtSignUp = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JLabel();
        frameBlue = new javax.swing.JLabel();
        backgroundWhite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(829, 449));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFullName.setBackground(new java.awt.Color(255, 255, 255));
        txtFullName.setForeground(new java.awt.Color(0, 0, 0));
        txtFullName.setBorder(null);
        txtFullName.setMaximumSize(new java.awt.Dimension(240, 17));
        txtFullName.setMinimumSize(new java.awt.Dimension(240, 17));
        txtFullName.setPreferredSize(new java.awt.Dimension(240, 17));
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 260, 20));

        backgroundName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        getContentPane().add(backgroundName, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 134, 270, 37));

        txtEmailAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailAddress.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailAddress.setBorder(null);
        txtEmailAddress.setMaximumSize(new java.awt.Dimension(270, 17));
        txtEmailAddress.setMinimumSize(new java.awt.Dimension(240, 17));
        txtEmailAddress.setName(""); // NOI18N
        txtEmailAddress.setPreferredSize(new java.awt.Dimension(270, 17));
        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 207, 250, 20));

        dEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        getContentPane().add(dEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 202, 270, 37));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setBorder(null);
        txtPassword.setMaximumSize(new java.awt.Dimension(250, 30));
        txtPassword.setMinimumSize(new java.awt.Dimension(250, 30));
        txtPassword.setPreferredSize(new java.awt.Dimension(230, 30));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 277, 250, 20));

        dPassword.setForeground(new java.awt.Color(0, 0, 0));
        dPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        getContentPane().add(dPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 270, 270, 37));

        txtFullNameDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoFullName.png"))); // NOI18N
        txtFullNameDesign.setMaximumSize(new java.awt.Dimension(91, 29));
        txtFullNameDesign.setMinimumSize(new java.awt.Dimension(91, 29));
        txtFullNameDesign.setPreferredSize(new java.awt.Dimension(91, 29));
        getContentPane().add(txtFullNameDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 105, 91, 29));

        txtEmailDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoEmail (2).png"))); // NOI18N
        txtEmailDesign.setMaximumSize(new java.awt.Dimension(91, 29));
        txtEmailDesign.setMinimumSize(new java.awt.Dimension(91, 29));
        txtEmailDesign.setPreferredSize(new java.awt.Dimension(91, 29));
        getContentPane().add(txtEmailDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 175, 91, 29));

        txtPasswordDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/textoPassword.png"))); // NOI18N
        txtPasswordDesign.setMaximumSize(new java.awt.Dimension(91, 29));
        txtPasswordDesign.setMinimumSize(new java.awt.Dimension(91, 29));
        txtPasswordDesign.setPreferredSize(new java.awt.Dimension(91, 29));
        getContentPane().add(txtPasswordDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 243, 91, 29));

        designSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign Uptopo.png"))); // NOI18N
        designSignUp.setMaximumSize(new java.awt.Dimension(164, 40));
        designSignUp.setMinimumSize(new java.awt.Dimension(164, 40));
        designSignUp.setPreferredSize(new java.awt.Dimension(164, 40));
        getContentPane().add(designSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 26, 164, 40));

        nuvemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuvem.png"))); // NOI18N
        getContentPane().add(nuvemIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 26, 25, 16));

        taskNotesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SkyNotes.png"))); // NOI18N
        taskNotesIcon.setMaximumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setMinimumSize(new java.awt.Dimension(119, 34));
        taskNotesIcon.setName(""); // NOI18N
        taskNotesIcon.setPreferredSize(new java.awt.Dimension(119, 34));
        getContentPane().add(taskNotesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 17, 119, 40));

        womanSkateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/skatewomanicon.png"))); // NOI18N
        womanSkateIcon.setToolTipText("");
        womanSkateIcon.setMaximumSize(null);
        getContentPane().add(womanSkateIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 302, 259));

        txtSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign Upbtn.png"))); // NOI18N
        txtSignUp.setToolTipText("");
        txtSignUp.setMaximumSize(new java.awt.Dimension(75, 23));
        txtSignUp.setMinimumSize(new java.awt.Dimension(75, 23));
        txtSignUp.setPreferredSize(new java.awt.Dimension(75, 23));
        txtSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSignUpMouseClicked(evt);
            }
        });
        getContentPane().add(txtSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 338, 50, 23));

        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLogin.png"))); // NOI18N
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 332, 151, 37));

        frameBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame.png"))); // NOI18N
        getContentPane().add(frameBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 829, 449));

        backgroundWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUpScreen.png"))); // NOI18N
        getContentPane().add(backgroundWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 829, 449));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void clean() {
        txtEmailAddress.setText("");
        txtFullName.setText("");
        txtPassword.setText("");
    }
    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        // TODO add your handling code here:
        String name = txtFullName.getText();
        String email = txtEmailAddress.getText();
        String password = txtPassword.getText();
        try {

            if (name.isEmpty() || email.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Empty Field");
            } else {
                modelUser.setName_User(name);
                modelUser.setEmail_User(email);
                modelUser.setPassword_User(password);
                if (daoUser.insertUser(modelUser)) {
                    JOptionPane.showMessageDialog(null, "Registered successfully");
                }else{
                    JOptionPane.showMessageDialog(null, "Some information is invalid");
                }
            }
            clean();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void txtSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSignUpMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSignUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundName;
    private javax.swing.JLabel backgroundWhite;
    private javax.swing.JLabel btnSignUp;
    private javax.swing.JLabel dEmail;
    private javax.swing.JLabel dPassword;
    private javax.swing.JLabel designSignUp;
    private javax.swing.JLabel frameBlue;
    private javax.swing.JLabel nuvemIcon;
    private javax.swing.JLabel taskNotesIcon;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JLabel txtEmailDesign;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JLabel txtFullNameDesign;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JLabel txtPasswordDesign;
    private javax.swing.JLabel txtSignUp;
    private javax.swing.JLabel womanSkateIcon;
    // End of variables declaration//GEN-END:variables
}
